world: "plot"
height: 80
radius: 1000
message:
  command:
    no_permission: "권한 없음"
    nor_arg: "아규먼트 없음"
  buy:
    already_my_plot: "본인 플롯임"
    exist_plot_owner: "다른사람 플롯임"
    plot_limit: "플롯이 이미 최대 개수임"
    not_plot: "플롯이 아님"
    not_plot_world: "플롯 월드가 아님"
    over_radius: "범위 넘음"
    buy_plot: "플롯 구매!"
  info:
    not_plot: "플롯이 아님"
    not_plot_world: "플롯 월드가 아님"
  home:
    no_plot: "플롯이 없음"
    no_plot2: "플롯이 그 만큼 없음"
    teleport: "텔레포트함"
    error: "명령어 에러"
  tp:
    no_arg: "좌표 입력하셈"
    over_radius: "범위 넘음"
    teleport: "텔레포트함"
    error: "명령어 에러"
  helper:
    no_arg: "argument 부족함"
    not_plot_world: "플롯 월드가 아님"
    no_player_data: "데이터가 존재하지 않는 플레이어임"
    no_owner: "주인이 없는 플롯"
    diff_owner: "주인이 다른 플롯"
    add: "그 플레이어를 도우미 목록에 추가함"
    sub: "그 플레이어를 도우미 목록에서 삭제함"
  deny:
    no_arg: "argument 부족함"
    not_plot_world: "플롯 월드가 아님"
    no_player_data: "데이터가 존재하지 않는 플레이어임"
    no_owner: "주인이 없는 플롯"
    diff_owner: "주인이 다른 플롯"
    add: "그 플레이어를 차단 목록에 추가함"
    sub: "그 플레이어를 차단 목록에서 삭제함"
  merge:
    not_plot_world: "플롯 월드가 아님"
    not_between: "플롯과 플롯 사이가 아님"
    no_owner: "주인이 없는 플롯"
    diff_owner: "주인이 다른 플롯"
    already_merged: "이미 병합된 플롯"
    not_merged: "인접한 플롯이 모두 병합된 상태가 아님"
    success: "병합 성공"
  detach:
    not_plot_world: "플롯 월드가 아님"
    no_owner: "주인이 없는 플롯"
    not_merged: "병합된 플롯이 아님"
    success: "병합 해제 성공"
  delete:
    not_plot_world: "플롯 월드가 아님"
    no_owner: "주인이 없는 플롯"
    success: "삭제 성공"
  move:
    no_arg: "좌표 입력하셈"
    not_plot_world: "플롯 월드가 아님"
    error: "명령어 에러"
    exist_owner: "이동 위치에 주인이 있음"
    over_radius: "범위 넘음"
    no_owner: "주인이 없는 플롯"
    success: "이동 성공"
  give:
    no_arg: "argument 부족함"
    not_plot_world: "플롯 월드가 아님"
    exist_plot_owner: "주인이 있는 플롯임"
    over_radius: "범위 넘음"
    no_player_data: "데이터가 존재하지 않는 플레이어임"
    success: "지급 성공"
  maxplot:
    no_arg: "argument 부족함"
    arg_error: "argument 에러!"
    no_player_data: "데이터가 존재하지 않는 플레이어임"
    error: "명령어 에러"
    success: "최대 개수 설정 성공"
  setskin:
    no_arg: "스킨 이름 입력"
    not_plot_world: "플롯 월드가 아님"
    no_owner: "주인 없는 플롯"
    no_data: "알 수 없는 스킨"
    success: "스킨 설정 성공"