world: "plot"
height: 80
radius: 1000
message:
  command:
    no_permission: "권한 없음"
  buy:
    already_my_plot: "본인 플롯임"
    exist_plot_owner: "다른사람 플롯임"
    plot_limit: "플롯이 이미 최대 개수임"
    not_plot: "플롯이 아님"
    not_plot_world: "플롯 월드가 아님"
    over_radius: "범위 넘음"
    buy_plot: "플롯 구매!"
  info:
    not_plot: "플롯이 아님"
    not_plot_world: "플롯 월드가 아님"
  home:
    no_plot: "플롯이 없음"
    no_plot2: "플롯이 그 만큼 없음"
    teleport: "텔레포트함"
    error: "명령어 에러"
  tp:
    no_arg: "좌표 입력하셈"
    over_radius: "범위 넘음"
    teleport: "텔레포트함"
    error: "명령어 에러"
  merge:
    not_plot_world: "플롯 월드가 아님"
    not_between: "플롯과 플롯 사이가 아님"
    no_owner: "주인이 없는 플롯"
    diff_owner: "주인이 다른 플롯"
    already_merged: "이미 병합된 플롯"
    success: "병합 성공"