world: "plot"
height: 80
radius: 1000
message:
  command:
    no_permission: "§a[Plot] §f명령어 권한이 없습니다."
    no_arg: "§a[Plot] §f플롯 명령어를 보려면 /plot help 를 입력하세요."
    wrong_command: "§a[Plot] §f잘못된 명령어입니다."
  buy:
    already_my_plot: "§a[Plot] §f이미 자신의 플롯입니다."
    exist_plot_owner: "§a[Plot] §f다른 플레이어의 플롯입니다."
    plot_limit: "§a[Plot] §f보유 플롯이 최대 개수를 넘었습니다."
    not_plot: "§a[Plot] §f그 곳은 플롯이 아닙니다."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    over_radius: "§a[Plot] §f너무 먼 플롯입니다."
    buy_plot: "§a[Plot] §f플롯을 구매했습니다!"
  info:
    not_plot: "§a[Plot] §f그 곳은 플롯이 아닙니다."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
  home:
    no_plot: "§a[Plot] §f플롯이 존재하지 않습니다."
    no_plot2: "§a[Plot] §f플롯이 그 만큼 없습니다."
    teleport: "§a[Plot] §f자신의 플롯으로 이동했습니다."
    error: "§a[Plot] §f숫자를 입력하세요."
    smaller_one: "§a[Plot] §f1 이상의 숫자를 입력하세요."
  tp:
    no_arg: "§a[Plot] §f좌표를 입력하세요."
    over_radius: "§a[Plot] §f너무 먼 플롯입니다."
    teleport: "§a[Plot] §f플롯으로 이동했습니다."
    error: "§a[Plot] §f숫자를 입력하세요."
  helper:
    no_arg: "§a[Plot] §f닉네임을 입력하세요."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    no_player_data: "§a[Plot] §f데이터가 존재하지 않는 플레이어입니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    diff_owner: "§a[Plot] §f다른 플레이어의 플롯입니다."
    add: "§a[Plot] §f그 플레이어를 도우미 목록에 추가했습니다."
    sub: "§a[Plot] §f그 플레이어를 도우미 목록에서 삭제했습니다."
    deny: "§a[Plot] §f차단 목록에 존재하는 플레이어입니다."
  deny:
    no_arg: "§a[Plot] §f닉네임을 입력하세요."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    no_player_data: "§a[Plot] §f데이터가 존재하지 않는 플레이어입니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    diff_owner: "§a[Plot] §f다른 플레이어의 플롯입니다."
    add: "§a[Plot] §f그 플레이어를 차단 목록에 추가했습니다."
    sub: "§a[Plot] §f그 플레이어를 차단 목록에서 삭제했습니다."
    helper: "§a[Plot] §f도우미 목록에 존재하는 플레이어입니다."
  merge:
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    not_between: "§a[Plot] §f플롯과 플롯 사이가 아닙니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    diff_owner: "§a[Plot] §f두 플롯의 주인이 다릅니다."
    already_merged: "§a[Plot] §f이미 병합된 플롯입니다."
    not_merged: "§a[Plot] §f인접한 플롯이 모두 병합된 상태가 아닙니다."
    success: "§a[Plot] §f플롯을 병합했습니다."
  detach:
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    not_merged: "§a[Plot] §f병합된 플롯이 아닙니다."
    success: "§a[Plot] §f플롯의 병합을 모두 해제했습니다."
  delete:
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    success: "§a[Plot] §f플롯을 삭제했습니다."
  move:
    no_arg: "§a[Plot] §f좌표를 입력하세요."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    error: "§a[Plot] §f숫자를 입력하세요."
    exist_owner: "§a[Plot] §f이동하고자 하는 위치에 이미 플롯이 존재합니다."
    over_radius: "§a[Plot] §f너무 먼 플롯입니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    success: "§a[Plot] §f플롯을 이동시켰습니다."
  give:
    no_arg: "§a[Plot] §f플레이어와 좌표를 입력하세요."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    exist_plot_owner: "§a[Plot] §f주인이 있는 플롯입니다."
    over_radius: "§a[Plot] §f너무 먼 플롯입니다."
    no_player_data: "§a[Plot] §f데이터가 존재하지 않는 플레이어입니다."
    success: "§a[Plot] §f플레이어에게 플롯을 지급했습니다."
  maxplot:
    no_arg: "§a[Plot] §f플레이어와 개수를 입력하세요."
    arg_error: "§a[Plot] §f숫자를 입력하세요."
    no_player_data: "데이터가 존재하지 않는 플레이어임"
    error: "§a[Plot] §f명령어 에러가 발생했습니다."
    success: "§a[Plot] §f플레이어의 플롯 최대 개수를 설정했습니다."
  setskin:
    no_arg: "§a[Plot] §f스킨 이름을 입력하세요."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    no_data: "§a[Plot] §f데이터가 존재하지 않는 스킨입니다."
    success: "§a[Plot] §f플롯의 스킨을 설정했습니다."
  clear:
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    success: "§a[Plot] §f플롯을 초기화했습니다."
  setbiome:
    no_arg: "§a[Plot] §f바이옴 이름을 입력하세요."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    success: "§a[Plot] §f플롯의 바이옴을 설정했습니다."
    wrong_biome: "§a[Plot] §f잘못된 바이옴입니다."
  list:
    no_player: "§a[Plot] §f데이터가 존재하지 않는 플레이어입니다."
  set:
    not_plot_world: "§a[Plot] §f그 곳은 플롯 월드가 아닙니다."
    no_owner: "§a[Plot] §f주인이 없는 플롯입니다."
    diff_owner: "§a[Plot] §f다른 플레이어의 플롯입니다."
    wrong_set: "§a[Plot] §f알 수 없는 설정입니다."
    wrong_value: "§a[Plot] §f알 수 없는 값입니다."
    success: "§a[Plot] §f플롯을 설정했습니다."